name: "Build"
on: [pull_request, push, workflow_dispatch]

permissions: {}

jobs:
  build: # make sure build/ci work properly
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - run: |
        npm install
        npm run all
