name: "Build"
on: [pull_request, push, workflow_dispatch]

permissions: {}

jobs:
  build: # make sure build/ci work properly
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - run: |
        npm install
        npm run all
